- components/projects/NewProject/NewProjectForm.tsx
- lib/hooks/useCustomers.ts
- lib/hooks/useEmployees.ts
- lib/hooks/useProjects.ts
- lib/utils/fetch.ts
- lib/utils/fetcher.ts
Based on feedback from @LeadingMoominExpert I implemented wrappers around fetch. Largely inspired by [this](https://eckertalex.dev/blog/typescript-fetch-wrapper) blog post.
> fetch wrappers

- README.md
- epoc-compose.yaml
The frontend should have a better readme file. What should the file include?
> chore: updated the readme

- epoc-compose.yaml
https://github.com/three-consulting/epoc-backend/pkgs/container/epoc-backend
> chore: update backend name to new package

- package.json
- yarn.lock
Run both local backend environment and frontend by simply running `yarn run dev-local`
> chore: run local server script

- .eslintrc.js
- .husky/pre-commit
- package.json
- yarn.lock
I could not get the changes in #53 to work for the life of my and I don't know why. I got it to work by installing lint staged with yarn and adding the configurations manually. Will close PR #53. Closes #30, closes #40.
> test: added lint-staged and the no-console rule for eslint

- README.md
Added documentation on how to use commitlint effectively.
> docs: updated docs on how to use commitlint

- .github/workflows/housekeeping.yml
- __tests__/component/form/CreateCustomerForm.test.tsx
- components/form/CustomerForm.tsx
- jest.config.js
- package.json
- yarn.lock
Introduce some basic tests that every form should pass and implement these for `CreateCustomerForm`:
* A form with only the required fields set is submitted correctly to the expected URL.
* A form with all fields set is submitted correctly to the expected URL.
* The method `afterSubmit` that [all forms have](https://github.com/three-consulting/epoc-frontend/blob/main/lib/types/forms.ts#L4) is invoked after submission as expected.
* The method `onCancel` that [all forms have](https://github.com/three-consulting/epoc-frontend/blob/main/lib/types/forms.ts#L5) is invoked on cancel as expected.
> test: tests for create customer form

- __tests__/fixtures.ts
- components/detail/ProjectDetail.tsx
- components/detail/TimesheetDetail.tsx
- components/form/ProjectForm.tsx
- components/form/TimesheetForm.tsx
- components/table/TimesheetTable.tsx
- lib/types/api.ts
After a backend [update](https://github.com/three-consulting/epoc-backend/pull/79), employee fields will be in camelcase.
> style: employee fields to camelcase

- __tests__/component/form/EditTimesheetForm.test.tsx
- __tests__/fixtures.ts
Same as #125 but commits squashed
> test: add tests for edit timesheet form

- components/table/TimesheetTable.tsx
> fix: format user table correctly on project page

- .github/workflows/housekeeping.yaml
Main branch already has it's own workflow so running the tests in two different workflows is kinda useless﻿
> chore: don't run housekeeping on main branch

- components/table/TaskTable.tsx
- components/table/TimesheetTable.tsx
We get stuff like this in the console in `main`. These changes should fix these.
> fix: fix console errors

- components/table/ReportTable.tsx
Some suggestions:
* Remove the repeated `Total hours for`.
* Remove the now-redundant `Total hours per project`
* Replace `<br>`s with CSS.
> style: misc report page fixes

- components/table/ReportTable.tsx
> feat: filter report details by employee

- components/table/ReportTable.tsx
- pages/report/index.tsx
As far as I know, the functionality of the date picker is correct, but I'm uncertain how the error handling should be done. Now when the input is invalid a new error is thrown, but it's not displayed in any proper way so if you'd like a box or some other component to be shown just let me know.
> feat: date picker

- components/form/TimesheetForm.tsx
Fixes:
- Restricted _allocation_ and _rate_ fields' inputs to only numbers
- _Allocation_ can have a value between 0 and 100
- _Rate_ can have value of 0 and greater
- Add error message for invalid _rate_
> Bug: fix rate and allocation validation

- components/common/LeftNav.tsx
- components/common/Main.tsx
- lib/contexts/FirebaseAuthContext.tsx
- Control user state in Main-component
- Hide all but sign in link if user is not logged in
> fix: hide all but sign in when user is logged out

- components/form/CustomerForm.tsx
- components/form/TaskForm.tsx
- components/form/TimesheetForm.tsx
> feat: display invalid input in a sleeker way

- __tests__/fixtures.ts
- lib/types/api.ts
- lib/types/typeMetadata.ts
- package.json
- Changed types script to use heroku as source
- Updated types
- Fixed types of employees in tests
> Updated types to match with backend

- .github/workflows/housekeeping.yaml
- .github/workflows/pull-request.yaml
- package.json
- Added Github actions for pull request
- Updated type validation scripts
- Updated main and housekeeping actions with correct type validation scripts
> Updated Github actions for type validation and added actions for pull request

- .eslintrc.js
- components/common/LeftNav.tsx
- components/common/Main.tsx
- lib/hooks/useFirebaseAuth.ts
- lib/types/auth.ts
- hide projects, customers, and reports links from the left nav if user is not an admin
> feat: hide navigation links from non admin users

- components/editor/TimesheetEntryEditor.tsx
> feat: display hours made in a month

- __tests__/component/form/CreateCustomerForm.test.tsx
- __tests__/component/form/CreateEmployeeForm.test.tsx
- __tests__/component/form/CreateProjectForm.test.tsx
- __tests__/component/form/CreateTaskForm.test.tsx
- __tests__/component/form/CreateTimesheetForm.test.tsx
- __tests__/component/form/EditCustomerForm.test.tsx
- __tests__/component/form/EditEmployeeForm.test.tsx
- __tests__/component/form/EditProjectForm.test.tsx
- __tests__/component/form/EditTaskForm.test.tsx
- __tests__/component/form/EditTimesheetForm.test.tsx
- __tests__/fixtures.ts
- components/common/FormFields.tsx
- components/common/LeftNav.tsx
- components/common/WarningModal.tsx
- components/detail/EmployeeDetail.tsx
- components/form/EmployeeForm.tsx
- components/table/EmployeeTable.tsx
- lib/hooks/useDetail.ts
- lib/hooks/useUpdate.ts
- lib/types/api.ts
- pages/customer/[id]/edit.tsx
- pages/employee/[id]/edit.tsx
- pages/employee/[id]/index.tsx
- pages/employee/index.tsx
- pages/project/[id]/edit.tsx
- pages/project/[id]/index.tsx
- pages/timesheet/[id]/edit.tsx
- pages/timesheet/[id]/index.tsx
- Added new form for editing and creating employees
- Fixed async code anti patterns from tests
> 237 frontend admin page for updating employee data and role

- __tests__/component/form/CreateTimesheetEntryForm.test.tsx
- __tests__/fixtures.ts
- components/form/TimesheetEntryForm.tsx
Added tests for create timesheet entry form
> 175 tests for createtimesheetentryform

- __tests__/component/form/CreateCustomerForm.test.tsx
- __tests__/component/form/CreateEmployeeForm.test.tsx
- __tests__/component/form/CreateProjectForm.test.tsx
- __tests__/component/form/CreateTaskForm.test.tsx
- __tests__/component/form/CreateTimesheetEntryForm.test.tsx
- __tests__/component/form/CreateTimesheetForm.test.tsx
- __tests__/component/form/EditCustomerForm.test.tsx
- __tests__/component/form/EditEmployeeForm.test.tsx
- __tests__/component/form/EditProjectForm.test.tsx
- __tests__/component/form/EditTaskForm.test.tsx
- __tests__/component/form/EditTimesheetEntryForm.test.tsx
- __tests__/component/form/EditTimesheetForm.test.tsx
Refactored the form tests to be used as intended:
- Got rid of then...catch syntax
- Got rid of unnecessary async iteration
> Refactor form tests

- README.md
- package.json
A proposal to rename dev scripts :) TODO:  fix gh actions if this propsal proceeds
> update dev script name

- components/common/AuthErrorAlert.tsx
- components/table/ReportTable.tsx
- pages/employee/index.tsx
- pages/report/index.tsx
- Added new error alert component for unauthorized errors
- The alert will be similar in all pages and therefore own component is useful
- Implemented the new component in pages of:
- Employee
- Report
> Handle unauthorized errors with auth error alert

- components/common/LeftNav.tsx
- Fixed left navigation buttons  whole area of element to be responsive
> fix: left nav buttons whole area responsive

- components/table/ReportTable.tsx
- Removed search button
- Removed unnecessary component state
- Report page is updated whenever date values change
> feat: report page is updated whenever date is changed

- components/detail/EmployeeDetail.tsx
- components/form/CustomerForm.tsx
- components/form/EmployeeForm.tsx
- pages/customer/[id]/edit.tsx
- pages/customer/[id]/index.tsx
- pages/employee/[id]/edit.tsx
- pages/employee/[id]/index.tsx
- pages/project/[id]/edit.tsx
- pages/project/[id]/index.tsx
- New styles to employee form
- Fixed all form styles to be identical
> 291 employee form page is missing the new style components

- components/table/ReportTable/utils.ts
Added sorting for timesheet entries into pdf export
> fix: sort entries in pdf export

- components/detail/EmployeeDetail.tsx
> Show status on employee details page

- components/form/ProjectForm.tsx
- components/form/TimesheetForm.tsx
> Filter archived employees from form selections

- components/form/EmployeeForm.tsx
- components/form/FromCsvForm.tsx
- components/form/ProjectForm.tsx
- components/form/TimesheetEntryForm.tsx
- components/form/TimesheetForm.tsx
- components/table/ReportTable/FilterFields.tsx
> Remove placeholders from Select components

- components/table/ReportTable/DateInput.tsx
- components/table/ReportTable/TableButtons.tsx
- components/table/ReportTable/utils.ts
> Group report-pdf by employee

- components/common/FormFields.tsx
- components/common/StyledButtons.tsx
- components/form/CustomerForm.tsx
- components/form/EmployeeForm.tsx
- components/form/ProjectForm.tsx
- components/form/TaskForm.tsx
- components/form/TimesheetEntryForm.tsx
- components/form/TimesheetForm.tsx
- components/modal/ImportFromCSVModal.tsx
- components/table/CustomerTable.tsx
- components/table/EmployeeTable.tsx
- components/table/ProjectTable.tsx
- components/table/ReportTable/TableButtons.tsx
- components/table/TaskTable.tsx
- components/table/TimesheetTable.tsx
- pages/customer/[id]/index.tsx
- pages/employee/[id]/index.tsx
- pages/project/[id]/index.tsx
- pages/timesheet/[id]/index.tsx
> Limit the working hours on entry form

- components/table/ReportTable/utils.ts
> Add first page to exported pdf reports

- components/table/ReportTable/utils.ts
> Fix hour grouping on pdf export

- components/editor/TimesheetEntryEditor/index.tsx
- lib/hooks/misc.ts
> Show employee flex

- components/editor/TimesheetEntryEditor/index.tsx
- styles/Calendar.css
> Calendar tooltip for entries

- package.json
- yarn.lock
This reverts commit 8a9d616b62a36e6a9702a59b47e555751e9b3ddf.
> Revert "Bump next from 12.3.4 to 13.4.19"

- .gitignore
- Dockerfile
- nginx.conf.tmpl
I guess nginx needs to know the mimetypes of static files, and those are listed here https://www.nginx.com/resources/wiki/start/topics/examples/full/#mime-types
> Fix nginx file serving
